### ISSUE TITLE
TransitionMotion

### ISSUE THREAD

**Issue by kristian-puccio** [nkbt/react-collapse#12]
Do you think it would work to use TransitionMotion?

I have some dynamic content basic on flux data and I would like to be able to get rid of the content but still have it visible while it is closing.

**Comment by nkbt** [comment]
Hi, @kristian-puccio 
I don't think it should not, unless you manually replace it with `null` or something. When Collapse is collapsed it removes all it's children.

Though being honest, I've never used TransitionMotion myself and can't say for sure if there are any gotchas. Would be awesome to hear about your experience. If all is good - feel free to shoot a PR with example and/or readme update, if not - let's debug it and fix it (if it is fixable).

So far I've seen one pretty nasty gotcha (completely unrelated): #9, using floating elements inside Collapse, so it's "wrapper" div has always `hight = 0`...

**Comment by kristian-puccio** [comment]
Ok I'll give it a go. When I have time I have to have more of  a play with TransitionMotion.

I'll send a PR if things work out.

Cheers

**Comment by nkbt** [comment]
:ok_hand:
