### ISSUE TITLE
Component Seems to Disappear for a Brief Second

### ISSUE THREAD

**Issue by fbgrecojr** [nkbt/react-collapse#122]
[
![gif](https://cloud.githubusercontent.com/assets/10980936/19415330/bd0ce5fc-9332-11e6-96de-c9f517fcec47.gif)
](url)

Component seems to disappear or flicker for a brief second even before `isOpened` is set to false. In the example above, when I close the `Message` component, it fades out and then after, `isOpened` is set to false; Something funky seemed to be happening to`Collapse` when the close icon is clicked.

**Message.js**

```
import React, {PropTypes, Component} from 'react';
import MessageTypes from '../constants/MessageTypes';
import Collapse from 'react-collapse';

export default class Message extends Component {

    constructor(props, context) {
        super(props, context);
        this.handleClick = this.handleClick.bind(this);
        this.onAnimationEnd = this.onAnimationEnd.bind(this);
        this.state = {
            animate: false,
            hide: false
        }
    }

    handleClick(e) {
        e.preventDefault();
        this.setState({animate: true});
    }

    onAnimationEnd() {
        this.setState({hide: true});
    }

    render() {
        return (
            <Collapse isOpened={!this.state.hide}>
                <div onAnimationEnd={this.onAnimationEnd} className={`card message ${this.state.animate ? 'message-transition-fade-out' : ''}`}>
                    <span className={`icon icon-${this.iconLevel()}`} style={{color: `#${this.iconColor()}`}}></span>
                    <p>
                        <strong>{this.props.title}</strong><br />
                        <span dangerouslySetInnerHTML={{ __html: this.props.message }} />
                    </p>
                    <a href="#" onClick={this.handleClick}>
                        <span className="icon icon-close"></span>
                    </a>
                </div>  
            </Collapse>
        );
    }

}
```

**Message.scss**

```
.message {
    &-transition {
        &-fade-out {
            @include animation(0s, 3s, fadeout);
        }
    }
}
```

**Comment by nkbt** [comment]
Can you please check with react-collapse@3? Should not disappear as far as
I know

**Comment by fbgrecojr** [comment]
I am still getting the save behavior in v3.2.0. Before I was using v2.3.3

**Comment by fbgrecojr** [comment]
Alright so I was trying some things and I set `keepCollapsedContent={true}` and now I have mixed results. Sometimes it works like I want it to and sometimes it dosen't. Here's a long 18 second GIF: the first time it doesn't work but after a refresh it works like I want it to.
[
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/10980936/19418954/21539e6e-9394-11e6-87d8-cc107d749d1a.gif)](https://cloud.githubusercontent.com/assets/10980936/19418954/21539e6e-9394-11e6-87d8-cc107d749d1a.gif)

Now I have to idea what `keepCollapsedContent` does under the hood that would make it work *sometimes*. Is there documentation for this project?

**Comment by nkbt** [comment]
Check the readme on master branch (default is 2.x, so you need to switch
it). It has all the most recent docs

Cheers 🍻

**Comment by fbgrecojr** [comment]
Any comment on the difference in the collapse animation between the browsers?

**Comment by nkbt** [comment]
I've never experienced any so far. Can get through your examples in detail,
away from my laptop now.

Usually diff comes from browsers dealing differently with paddings/margins
and other height-related styles. I try to never use any margins/paddings in
collapse-related elements (and sometimes children) and it works out well
