### ISSUE TITLE
Event triggers for completing collapse and expand

### ISSUE THREAD

**Issue by haack** [nkbt/react-collapse#126]
I've found a use case where it would be useful to have optional onCollapseComplete and onExpandComplete callbacks.

If other people would find this useful then I'd be happy to implement it properly and raise a PR

**Comment by nkbt** [comment]
That looks like useful thing, though I usually know if it is opened/closed
and use onRest callback. Seems very much sufficient for the case

**Comment by nkbt** [comment]
Does not look much useful, apparently
