### ISSUE TITLE
Why there is delay when opening the collapse ?

### ISSUE THREAD

**Issue by kopax** [nkbt/react-collapse#147]
I am comparing __react-collapse__ with [bootstrap 4 and it's navbar collapse menu](https://v4-alpha.getbootstrap.com/components/navbar/).

Why is the bootstrap 4 effect more fluid and is it possible to have the same ?

**Comment by nkbt** [comment]
Because it uses Spring animation. See https://github.com/chenglou/react-motion for details

**Comment by kopax** [comment]
I have read the doc, is it possible for you to share the details ?

**Comment by nkbt** [comment]
So if http://nkbt.github.io/react-collapse/example/ is good, then delay in your app is something about your app, I reckon...

**Comment by kopax** [comment]
Where can I find the example source code?

**Comment by kopax** [comment]
I have remove a component with a Hudge jsx content under my test and then it went fluid again.
I guess I should move the effect to it's own component so it doesn't rerender the whole thing.

**Comment by nkbt** [comment]
yep, pretty usual problem when using `react-motion`. Need a proper sub-components caching with `shouldComponentUpdate`
