### ISSUE TITLE
Expanding much quicker than collapsing

### ISSUE THREAD

**Issue by bdmason** [nkbt/react-collapse#152]
When no fixed height is set expanding is much faster than collapsing when `react-collapse` is used on longer content.

Using fixed height won't work for me as I'm using a form where error messages are sometimes present, so there is no single fixed height for each viewport unless I calculate the height based on all visible errors and their height - for each viewport - which would be really tedious.

I'm simply trying to replicate `jQuery.slideToggle()` and feel like I'm missing a simple setting. In case it's relevant, I'm using a nested `<Collapse>`, the parent (a bit further up the DOM) of which is `<Collapse isOpened={open} hasNestedCollapse={true}>`

**Comment by nkbt** [comment]
1. Try react-collapse@3
2. Hight might not be calculated properly, so when expanding content is huge, but ehen collapsing - content hight is determined to be much smaller.

Without codepen/jsbin it is impossible to give any more help

**Comment by bdmason** [comment]
Thanks for the extremely quick reply!

I'm on 3.2.0 as I needed that for a nested content issue previously.

I'm about to go out the office for lunch, so if I don't get it sorted shortly after I'll get an account on codepen and get something up there.

If this helps highlight a potential issue - giving it a fixed height didn't change anything, still much faster when expanding.

**Comment by nkbt** [comment]
You can use example from readme on codepen as reference if you need it

**Comment by bdmason** [comment]
I've edited example 2, replaced the div with a lot of hr tags and it's [replicated the issue](http://codepen.io/bdmason/pen/bqmGmQ)

**Comment by nkbt** [comment]
I'll have a look tomorrow. It's almost midnight here in Sydney now...

**Comment by bdmason** [comment]
For when you get chance to look at it - I removed the content height in the forked codepen linked above, so the slider no longer does anything on example 2.

**Comment by bdmason** [comment]
After further investigation, it seems to be the default behaviour of react-motion and has nothing to do with variable heights or react-collapse itself.

Generally, the default behaviour is nice, but when you have long sections to expand (the one I'm working on is 1074px), it's not very nice as you either have to have an uncomfortably fast expansion or a really slow collapse.

So far, editing the spring and damping doesn't seem to help either, but this is the first time I've worked with animation settings like this, so I may have some luck when I gain more understanding.

**Comment by nkbt** [comment]
Ah, yeah. You are totally right in the last comment. It is all about spring-based animation. When you have a very large list it is definitely noticeable. I am afraid there is not much you can do about it now.

I have a plan to move away from react-motion in react-collapse for almost the same reason. It is way too often we do not want spring animation and want a simple linear animation instead. But currently we are very busy at work and this has much lower priority in the backlog =(.

**Comment by bdmason** [comment]
By playing with the stiffness I've got it slowed down a little so the expand isn't too fast, and the collapse is only a little slower than I'd like.

You may already be aware as it seems it's been around for a while, but I stumbled across [React Fiber](https://github.com/acdlite/react-fiber-architecture) last night, and it seems that a big part of that is incorporating animations (via incremental rendering), so it may be worth having a gander at that.

Thanks for your time with this module, it's helped the project I'm working on a lot.

**Comment by nkbt** [comment]
Thanks!
