### ISSUE TITLE
Feature to disable animation?

### ISSUE THREAD

**Issue by BrainB** [nkbt/react-collapse#153]
Hello, 

 I am using this with component that can have children components appended by user interactions. And every append to parent trigger rerender and show animation again. What would be best way to avoid this?

Is there way to disable component?

If I use this with state like this:

```
data=<Component....>
if (this.state.isCollapseActive) {
    data = <Collapse keepCollapsedContent={true}  isOpened={this.state.open} springConfig=springConfig}>
                        {data}
                    </Collapse>
}

return data;
```

Then on rerender I get scrolled back to top...

**Comment by nkbt** [comment]
You can wrap your `Component` into `div` and not use Collapse under certain conditions.

I also suggest to switch to react-collapse@3, which should work with fewer issues.

**Comment by BrainB** [comment]
Hello, I have tried **react-collapse@3** and used it like this:
```
 <Collapse hasNestedCollapse  isOpened={open} springConfig={springConfig}>
                        {children}
   </Collapse> );
```
But there is still same problem, when I rerender children components animation is triggered:

![2017-04-04 20h59_39](https://cloud.githubusercontent.com/assets/25670585/24673871/fc3cf5e6-1979-11e7-824e-aae26af3e0b0.gif)

And when I use second way and change between div and Collapse like this:

```
     if (active) {
          return (  <Collapse hasNestedCollapse  isOpened={open} springConfig={springConfig}>
                        {children}
                    </Collapse> );
         } else {
            return (
                <div>
                    {children}
                </div>
            )
        }
```

When changing render from <div> to <Collapse> so activating Collapse , then because of rerender I am jumped back to top of component.
