### ISSUE TITLE
Expand/collapse at fixed speed

### ISSUE THREAD

**Issue by AlecRust** [nkbt/react-collapse#154]
I notice react-collapse changes the `height` value as the panel is collapsing/expanding to achieve the animation (rather than two different heights and something like `transition: height 0.3s;`).

Does this mean react-collapse is able to expand/collapse at the same speed regardless of height of content? This is the feature I am looking for but can't find configuration for it.

With the CSS approach I mention the speed of expand/collapse will depend on how much content needs to be collapsed in 0.3s. I'm looking to set the speed of slide, not the duration of slide.

**Comment by nkbt** [comment]
It is not possible with current implementation that uses Spring animation. I have a task to do it eventually but no estimations
