### ISSUE TITLE
Add react-motion (and maybe react as well) as general dependency

### ISSUE THREAD

**Issue by lumio** [nkbt/react-collapse#169]
Hello,

is there a reason, why react-motion and react are not in the general dependency section?

Greetings 😀

**Comment by nkbt** [comment]
They are common widely used libraries and their versions in the project may differ from versions used in this library.

Some quite old post about peerDeps and what it is.
https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by lumio** [comment]
Makes sense! Thanks!
