### ISSUE TITLE
Callstack error with nested collapse elements

### ISSUE THREAD

**Issue by davidspiess** [nkbt/react-collapse#17]
I have following nested collapse boxes:

```
RoomSelection Collapse Box
   - Offer Collapse Box 1
          - Room Collapse Box 1
          - Room Collapse Box 2
          - Room Collapse Box 3
   - Offer Collapse Box 2
         ....
```
If i toggle more then one of the room collapse boxes i get a `Uncaught RangeError: Maximum call stack size exceeded` error and it takes aprox. 5 seconds until it opens. See gif

![gif](https://cloud.githubusercontent.com/assets/992674/11744850/10486ca4-a014-11e5-8291-aba265f95beb.gif)

Any ideas what could cause this?
Not nested collapse elements work just fine.

**Comment by nkbt** [comment]
@davidspiess I'll have a look into that asap.Nested elements used to work fine before

**Comment by nkbt** [comment]
I see you have a fairly complex content in there. I will try to re-create multiple nested components and see how it goes. There might be some issue with your internal components. If you re-render all subtree - like no `shouldComponentUpdate` or not very effective one

To check that - add console.log to your render() methods to different sub-components.

This point is not something react-collapse specific, but more React-specific perf optimization in general.

**Comment by davidspiess** [comment]
You are right, when clicking on the toggle button, it rerendered all of the siblings too.
This fixed my issue :+1:

**Comment by nkbt** [comment]
Awesome! Cheers.
