### ISSUE TITLE
2.4.0 breaks support for previous versions of react

### ISSUE THREAD

**Issue by DeeLindesay** [nkbt/react-collapse#173]
2.4.0 broke support for our version of React (currently 0.14.9).

**Comment by nkbt** [comment]
I am sorry for causing this trouble. Will fix compatibility issue and
publish patch release asap

-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by nkbt** [comment]
Fixed by https://github.com/nkbt/react-collapse/pull/174

See https://github.com/nkbt/react-collapse/releases/tag/v2.4.1 for some notes (not required, but generally useful)

**Comment by DeeLindesay** [comment]
Thank you
