### ISSUE TITLE
TypeError: Super expression must either be null error on react collapse 2.2.4

### ISSUE THREAD

**Issue by cutovoi** [nkbt/react-collapse#175]
I'm using React collapse in my project, version 2.2.4 with react 0.14.8. When It is loaded I have this problem.

`TypeError: Super expression must either be null or a function, not undefined  application.js`

I changed react to newest version and react-collapse too. Even with the change, this problem persists.
I found [this link](https://github.com/nkbt/react-collapse/issues/168) which appears to be useful for me, but no success.

This is the function where error occurs:

`function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
`
And those are the dependencies:

`"dependencies": {
    "babelify": "7.2.0",
    "browserify": "12.0.1",
    "browserify-incremental": "3.0.1",
    "jquery": "2.2.0",
    "react": "0.14.8",
    "react-bootstrap": "0.28.1",
    "react-collapse": "2.2.4",
    "react-dom": "0.14.3",
    "react-height": "2.1.0",
    "react-highcharts": "8.0.2",
    "react-motion": "0.4.4",
    "react-select": "1.0.0-beta12",
    "react-sticky-position": "2.0.0",
    "screenfull": "3.0.0"
  }`

**Comment by nkbt** [comment]
Never seen this. I can't even tell if it is related to collapse or your project. Could be some browserify-related thing. I do not use browserify and do only webpack, so I cannot help unless you have some minimal repo with this error I can try myself

**Comment by nkbt** [comment]
Closing as there are no more details for now...
