### ISSUE TITLE
Force rerender when inline image is loaded

### ISSUE THREAD

**Issue by lumio** [nkbt/react-collapse#176]
Hey,

as you might have guessed: I load an image based on the user input. Now somehow, the image gets cut off at the first render (as seen in the picture below), but when I change the state of the parent again, it rerenders with the correct height.

![rerender](https://cloud.githubusercontent.com/assets/914637/25713904/97999c54-30f6-11e7-806e-bfa13353816f.gif)

I wonder if there is a way to force react-collapse to rerender as well after loading the image file.

I'm using react-collapse@4.0.2

**Comment by nkbt** [comment]
Must be related to https://github.com/nkbt/react-collapse/pull/166

If you can check that PRs version in your case that would be extremely helpful. 

Or maybe give a codepen so we can play with it

**Comment by lumio** [comment]
Thanks for your answer! I updated my initial comment, mentioning the version of react-collapse (4.0.2)

I am wondering, if it would be a good idea to remove the `overflow: hidden` property when the container is fully expanded and only reuse it when react-collapse is being animated. And each time before it is going to shrink again, the height is being calculated. If that made any sense at all

**Comment by nkbt** [comment]
This is what is happening. Overflow is reset to auto. There is an edge case
when collapse stays in waiting state which that open pr tries to resolve...
we'll get there eventually.
There are really so many different edgecases and fixing one easily breaks
several other. That makes it so difficult to keep collapse "bug free" :(.


-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by nkbt** [comment]
I think we should add some low level way (maybe even not mentioned in
readme) to reset state or recalc height or smth similar so in case of like
yours it is possible to hack some one-off solution


>
> --
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by lumio** [comment]
Exactly, I thought of the same. So what I thought of doing is setting an onLoad event on the image, which then could trigger another rerender event - but I am wondering how to do this

**Comment by nkbt** [comment]
You can add some non-existent classname or Id or any other legal html prop
to Collapse and then remove it after setTimeout(0). Effectively rendering
twice (ok since react would render only difference).

-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by nkbt** [comment]
Must be fixed in `react-collapse@4.0.3`... check it out
