### ISSUE TITLE
ARIA Roles

### ISSUE THREAD

**Issue by AlecRust** [nkbt/react-collapse#177]
Have you thought about adding an option for ARIA roles?

For e.g. I have an accordion header with `role="tab"`, it would be nice if the top level `.ReactCollapse--collapse` element had `role="tabpanel"`.

There are also `aria-expanded` and `aria-controls` attributes which could be added.

**Comment by nkbt** [comment]
Collapse just passes all supplied props to the collapse element, so you should be able to add any props you want.
