### ISSUE TITLE
Animation doesn't complete if wrapper has `border` & `box-sizing: border-box`

### ISSUE THREAD

**Issue by NeonPaul** [nkbt/react-collapse#179]
Using a class like this:

```css
* {
  box-sizing: border-box;
}

.wrapper {
  border-top: 1px solid black;
}
```
```javascript
<Collapse className='.wrapper' isOpened={this.state.open}>...</Collapse>
```

I found that the container never finished opening and cut off some content at the bottom. It was stuck in the state RESIZING, and there was 1px difference between the `from` and `to` states. I assume this is because of the 1px difference in the border.

Not sure how hard this is to fix, but I spent ages trying to figure out what the problem was, so at least a line in the docs would be useful.

The workarounds are to set `box-sizing: content-box` on the `.wrapper` class, or to move the wrapper class onto a new div wrapping the children of Collapse.

**Comment by nkbt** [comment]
Should be fixed in `react-collapse@4.0.3`
