### ISSUE TITLE
An option to keep the node (not return null) when the height is zero

### ISSUE THREAD

**Issue by sompylasar** [nkbt/react-collapse#18]
This is required when applying CSS transitions (e.g. for background color).
When unmounted (`null` returned from `render`), the node loses its CSS state so when re-mounted, it gets fresh CSS state, and the transitions start over.

**Comment by nkbt** [comment]
I reckon that makes sense. Keen to PR?

**Comment by nkbt** [comment]
New opt-in feature to keep collapsed content `keepCollapsedContent` (defaults to `false`)

![keep-collapsed](https://cloud.githubusercontent.com/assets/175264/11917642/fe0237c6-a763-11e5-856f-bf60c48c5ef7.gif)

**Comment by nkbt** [comment]
Published as 1.6.0 https://github.com/nkbt/react-collapse/releases/tag/v1.6.0

**Comment by sompylasar** [comment]
@nkbt Yay that's perfect! Thanks!

**Comment by nkbt** [comment]
Cheers! I had a fair amount of pain with this, but everything is solved now
as far as I can test it. Check out the demo on gh-pages to see it in action
:)

**Comment by KyleAMathews** [comment]
Just a thought — any reason not to default this to true? Using this module for a client project (w/ Gatsby) and I noticed that before enabling this, there was some noticeable jumping in the animation right around when I assume the element was being destroyed. After I enabled this, the animation became super smooth.
