### ISSUE TITLE
Conflict with CSSTransitionGroup

### ISSUE THREAD

**Issue by jonom** [nkbt/react-collapse#180]
I noticed that if you have a `Collapse` component anywhere inside a `CSSTransitionGroup`, and `isOpened=true` when the Collapse element is mounted, the parent container of the Collapse item that is entering the CSSTransitionGroup doesn't play it's transition animation. The container receives all the right classes but it's as if it receives the `active` class at the same time as the other classes, so no change is recognised by the browser and the transition doesn't kick in.

Don't know if the cause is within the Collapse component or the CSSTransitionGroup but thought I would flag it... of course feel free to close this if you think it's out of scope.

Thanks for this handy component!

**Comment by nkbt** [comment]
I don't work with CSSTransitionGroup and don't have any plans to, so cannot help unfortunately

**Comment by nkbt** [comment]
As new react-collapse@5.0.0 is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been most likely already solved.

Please feel free to re-open if the issue persists
