### ISSUE TITLE
Set animation duration 

### ISSUE THREAD

**Issue by vivekiyer114** [nkbt/react-collapse#183]
how to set animation duration in this ?

**Comment by nkbt** [comment]
Spring animation does not operate time. You can play with spring stiffness, so it is faster or slower, but you cannot configure animation to have specific duration. 
Play with stiffness/dumping in example 5 http://nkbt.github.io/react-collapse/example/

**Comment by vivekiyer114** [comment]
Where is the code for setting stiffness ? 
I am not able to find it on your doc. 
Please Help me out with a link !
Thank you very much !

**Comment by nkbt** [comment]
It is in README

https://github.com/nkbt/react-collapse#springconfig-proptypesobjectofproptypesnumber
