### ISSUE TITLE
"jump" on uncollapse when there's more than one node

### ISSUE THREAD

**Issue by isaacalves** [nkbt/react-collapse#188]
I have the following structure:

```
          <Collapse
            isOpened={this.props.isOpen}
          >
            <p>test</p>
            <p>test</p>
            <p>test</p>
            <p>test</p>
            <p>test</p>
            <p>test</p>
          </Collapse>
```

I have a trigger that when clicked will toggle the opening of the Collapse element. It will re-render it with the `isOpen` props, and that works just fine, except that, if I have more than one node inside it, this is what happens:

![react-collapse bug](https://user-images.githubusercontent.com/1765942/29423649-6eecbe0a-8374-11e7-8dff-6d2101e33021.gif)

PS: This has been converted from MOV to GIF very poorly. The animation is actually quite smooth (good job!), but you can see that it expands as if there were only 5 elements, and by the end of the animation it will "jump" and expand a bit more, showing the last one. 

I tried wrapping a `<div>` around the `<p>` elements and nothing changes, still the jump.

**Comment by nkbt** [comment]
Most likely there are some margins involved (or inline elements with default margins , or floats, etc), so parent container has height that is smaller then height of all children. So when it expands and sets height to `auto` you see the jump.

This can only be solved (as far as I know) by styling your list items in the way that they do not expand beyond container boundaries.

**Comment by isaacalves** [comment]
Thanks a lot dude, that worked!
I just canceled <p>'s default margins. No problems with paddings.

**Comment by nkbt** [comment]
Glad it helped!
