### ISSUE TITLE
Link to the example gif in the Readme is wrong

### ISSUE THREAD

**Issue by mattgmarcus** [nkbt/react-collapse#194]
The link to the example gif in the Readme is currently https://github.com/nkbt/react-collapse/blob/master/src/example/react-collapse.gif

It looks like it should be https://github.com/nkbt/react-collapse/blob/master/example/react-collapse.gif

**Comment by nkbt** [comment]
Will happily accept PR =)

**Comment by mattgmarcus** [comment]
PR here https://github.com/nkbt/react-collapse/pull/195
