### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by Pau1fitz** [nkbt/react-collapse#196]
http://nkbt.github.io/react-collapse/

The demo at this page is broken.

Looks like the package  at https://unpkg.com/react@16.0.0/dist/react.min.js no longer exists

![screenshot from 2017-09-29 15-16-36](https://user-images.githubusercontent.com/6873736/31019916-389f5b4c-a529-11e7-9cf0-0f17402ad311.png)

**Comment by MartinKolarik** [comment]
The react files were renamed in the latest version. I recommend using [jsDelivr](https://www.jsdelivr.com/) in the future, which was built for production usage and guarantees that existing links never break:
 - https://cdn.jsdelivr.net/npm/react/dist/react.js
 - https://cdn.jsdelivr.net/npm/react-motion/build/react-motion.js
 - https://cdn.jsdelivr.net/npm/react-collapse/build/react-collapse.js

**Comment by nkbt** [comment]
Thanks for heads up. I will stick to unpkg. So need to use https://unpkg.com/react@16.0.0/umd/react.development.js or https://unpkg.com/react@16.0.0/umd/react.production.min.js (better prod for demo and dev for codepen).

**Comment by Kerumen** [comment]
@nkbt As of today, demo is still broken. Any fix planned?

**Comment by nkbt** [comment]
Fixed now. Both Codepen and Github pages
