### ISSUE TITLE
Nested Collapse components not visible on initial render

### ISSUE THREAD

**Issue by timecatalyst** [nkbt/react-collapse#197]
I'm experiencing a strange problem with nested collapse blocks not displaying their content on initial render, and triggering animations in the parent collapse block when they shouldn't.

When I run the following code, Neither the 'Foo' nor 'Bar' block is visible on initial render.

```
<Collapse isOpened={true} hasNestedCollapse={true}>
  <Collapse isOpened={true}>
    <div>Foo</div>
  </Collapse>
  <Collapse isOpened={true}>
    <div>Bar</div>
  </Collapse>
</Collapse>
```

However, if I add a `<div>` component adjacent to the nested `<Collapse>` components, it seems to force the initial render to show 'Foo' and 'Bar', but the open animation is triggered on the parent collapse block:

```
<Collapse isOpened={true} hasNestedCollapse={true}>
  <div>Test</div>
  <Collapse isOpened={true}>
    <div>Foo</div>
  </Collapse>
  <Collapse isOpened={true}>
    <div>Bar</div>
  </Collapse>
</Collapse>
```

I'm not sure if I'm doing something wrong, or if others are experiencing the same thing.

**Comment by nkbt** [comment]
Probably smth to do with styles of nested elements, so their height cannot
be determined reliably at the initial render. Cannot help much more at this
point without running example somewhere on codepen


-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by timecatalyst** [comment]
No worries.  Unfortunately I haven't been able to reproduce the behavior outside of my project, so I can only assume that there's a nebulous conflict with another library I'm using.  I'm not sure I have the time right now to really dig into it and figure out what may also be messing with the height, and since nobody else seems to be having this issue, it's probably fine to just close this issue.

For now it make sense for me to switch to the react-bootstrap Collapse, since I'm utilizing that library for a lot of other things already.
