### ISSUE TITLE
Use `visibility:hidden` in addition to `overflow:hidden`?

### ISSUE THREAD

**Issue by markwoon** [nkbt/react-collapse#198]
When the node is collapsed, would it be possible to use `visibility:hidden` in addition to `overflow:hidden`?

Right now, if I'm tabbing through links on a page, it will tab to links in collapsed nodes.  Adding `visibility:hidden` would prevent this from happening.

**Comment by selbekk** [comment]
You can actually do this yourself if you want - both with `aria-hidden` and `visibility: hidden` - by passing the props based on the `isOpened` prop.

**Comment by nkbt** [comment]
You can use `onRest` to add any extra classes to your element and define any extra css necessary for the resting component
