### ISSUE TITLE
Compatibility with React 16?

### ISSUE THREAD

**Issue by dimaip** [nkbt/react-collapse#200]
Is it compatible? If yes the peer dependency should be updated.

**Comment by nkbt** [comment]
```
 "react": ">=15.3",
```
Should match react@16 just fine

At least https://semver.npmjs.com/ says so...

**Comment by dimaip** [comment]
Ouch, my bad, looked at it from the other side LOL

**Comment by nkbt** [comment]
No worries!
Cheers
