### ISSUE TITLE
calculation of `height` not working if child has `position:fixed`

### ISSUE THREAD

**Issue by kkarkos** [nkbt/react-collapse#201]
When the first child element of  <Collapse> has the property `position:fixed` the inline-style stays at `height:0` and the animation does not get triggered on state change of `isOpened`. Work when `position` is set to relative.

**Comment by nkbt** [comment]
Yep, that is technically impossible to calculate.

Make parent fixed, put inside collapse and then all your content.

**Comment by nkbt** [comment]
So instead of

```jsx
<Collapse>
  <Fixed />
<Collapse>
```

Do 
```jsx
<FixedContainer>
  <Collapse>
    <AllStyledNotFixedContentHere />
  </Collapse>
</FixedContainer>
```
