### ISSUE TITLE
Empty parent collapse hides nested collapse

### ISSUE THREAD

**Issue by sjurlur** [nkbt/react-collapse#202]
If i have a nested collapse where the root has no other content than the nested collapse, height is set to 0 and child items are not shown. 

If i add content to the root in addition to child collapse, height gets calculated.

Works:
```
<Collapse isOpened hasNestedCollapse>
  content
  <Collapse isOpened>childContent</Collapse>
</Collapse>
```

Fails:
````
<Collapse isOpened hasNestedCollapse>
  <Collapse isOpened>childContent</Collapse>
</Collapse>
````

Example: https://codepen.io/sjurlur/pen/JOorNj

**Comment by nkbt** [comment]
As new `react-collapse@5.0.0` is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been most likely already solved.

Please feel free to re-open if the issue persists
