### ISSUE TITLE
Possible to disable animations?

### ISSUE THREAD

**Issue by eye1985** [nkbt/react-collapse#204]
Hi, 

Wondering if its possible to disable animatons?

**Comment by gnapse** [comment]
Not sure what sense does this makes.

The whole point of this library it to be able to animate the entrance and exiting of elements from the view. If you don't want the animation, then simply mark/unmark the element with `display: none` or render it conditionally only if expanded.

Am I missing something?

**Comment by ArkDeus** [comment]
There are some cases where it could be useful. For example, I have a lot of independant boards that can be  collapsed/expanded. I also have a button to collapse them all/show them all. 
When I collapse/show them all, there is a huge slowdown on the page since it has to compute 30-40 animations at the same time. That's why I would like to turn off animation when I have to collapse/show them all.

**Comment by ArkDeus** [comment]
Thanks a lot for your answer, for my case it didn't make sense at the end. Thank you for the piece of code.

**Comment by arianitu** [comment]
@nkbt Thats weird, why not just have a way to disable the animation? Right now we would have to create a custom <Collapse> on top of this component to handle the case where we want no animation, but a collapsable element.

Why not something like animation={false} and then we don't have to write a custom component? We are using <Collapse> for multiple use cases, but don't want to swap components between animated collapsable elements and non animated ones.

**Comment by nkbt** [comment]
Actually in current version I've switched to use CSS transitions, so it is trivial to do so. More on that version is in https://github.com/nkbt/react-collapse/issues/247

**Comment by nkbt** [comment]
As new `react-collapse@5.0.0` is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been already solved.

Just do not add css animations and open/close will be instant
