### ISSUE TITLE
Set `aria-expanded` property

### ISSUE THREAD

**Issue by selbekk** [nkbt/react-collapse#205]
Feature suggestion: Set the `aria-expanded` flag based on whether the element is collapsed or not.

What do you think? Are there use cases where you don't want this to be set, from an a11y point of view?

[Here's the spec](https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element)

I'd love to send a pull request for this, but thought it might be worth a discussion before I did so.

**Comment by nkbt** [comment]
Collapse passes all the props to it's element, so it is trivial to do that in the app.

Or create a small wrapper like
```jsx
const AriaCollapse = ({isOpened, ...rest}) =>
  <Collapse {...(isOpened ? {'aria-expanded': true} : {})} isOpened={isOpened} {...rest} />
```
without changing the library.

**Comment by selbekk** [comment]
Oh I totally agree it’s easy to fix from the consumer’s side - but shouldn’t aria tags be there by default? They are easy to forget to apply

**Comment by nkbt** [comment]
I don't think it should be part of lib, ReactCollapse tries to have only essential settings required to function and that technically cannot be applied on top of it. Everything that can be achieve from outside, should be done outside of base library in my opinion

**Comment by selbekk** [comment]
Very well :+1: Thanks for taking the time to consider it

**Comment by Mitchnsun** [comment]
With v5: any unknown props passed to Collapse component will be ignored
We couldn't set any aria-* for accessibility. Should I open a new issue for aria-expanded or aria-hidden ?

**Comment by nkbt** [comment]
To avoid re-renders

**Comment by Mitchnsun** [comment]
Thanks, I understand
