### ISSUE TITLE
Wrong height with dynamic content

### ISSUE THREAD

**Issue by tonoslav** [nkbt/react-collapse#206]
Hello, 

I have some panel with collapsable content but in one example I have a support form which has wrong height value calculated initially (red part is Collapse component)

![image](https://user-images.githubusercontent.com/3399021/33217782-d2b6ecea-d139-11e7-94d1-fd98f23aec5b.png)

And also when I focus into that Textarea, it will expand a little bit

![image](https://user-images.githubusercontent.com/3399021/33217799-ed84c236-d139-11e7-989d-8d8c01119fb1.png)

And button disappear completely (even it should not)

What could cause this problem?
How can I force it to recalculate height or how to make it dynamic?

If you need any css or jsx to see, just ask, but there is only isOpened and className attribute in Collapse in my project

Using v4.0.3

**Comment by nkbt** [comment]
It is probably because content elements have some padding/margin/border/etc
- sometging that is not included in innerHeight DOM property. Collapse uses
innerHeight so you need to make sure your css is limited accordingly to
avoid this sort of miscalculation
-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by tonoslav** [comment]
@nkbt 
margin: 15px -> padding: 15px fixed it 

but there is css rule
```less
textarea {
   height: 100px
   
   &:focus {
        height: 120px
   }
}
```

and after that focus, it is not recalculated, what can I do with that ?

Btw why don't you use outerHeight ?

**Comment by nkbt** [comment]
That is because height is changed with css. React has no idea about this change, component is not rerendered. I recommend set this height in JS with `style`. Or somehow make sure that on focus your component is updated.

**Comment by nkbt** [comment]
As new `react-collapse@5.0.0` is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been most likely already solved.

Please feel free to re-open if the issue persists
