### ISSUE TITLE
partial collapse

### ISSUE THREAD

**Issue by rr-kalbeck** [nkbt/react-collapse#212]
is it possible to partially collapse an element?
eg. i have several lines of text and i'd like to toggle between showing 3 lines and all lines

**Comment by nkbt** [comment]
I believe it is a duplicate of https://github.com/nkbt/react-collapse/issues/47
Look for solutions there

**Comment by nkbt** [comment]
I suggest solving it by limiting height if your children elements instead, Collapse will expand to it's height naturally.
