### ISSUE TITLE
Initial animation is not skipped in nested collapses

### ISSUE THREAD

**Issue by ardcore** [nkbt/react-collapse#215]
Hi,

Here's a pen: https://codepen.io/anon/pen/MQabej?editors=1010 -- as you can observe, the outer `Collapse` is rendered without the initial animation, but the nested one is animated, even though `isOpened` is set to true the component is initialised.

**Comment by nkbt** [comment]
As new `react-collapse@5.0.0` is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been most likely already solved.

Please feel free to re-open if the issue persists
