### ISSUE TITLE
Add class when expanded

### ISSUE THREAD

**Issue by CaptObvious** [nkbt/react-collapse#218]
For styling reasons, is it possible to add a class to the ReactCollapse--collapse div when expanded?  This would help with placing borders around the expanded box that aren't there when it's collapsed.

**Comment by Olliebaba** [comment]
@CaptObvious - You could toggle a class name stored in the parent's state using `onRest`. It might be weird though since borders impact layout. Why not just put the border on the child component that's hidden?

**Comment by nkbt** [comment]
Please use `onRest` for this sort of things, it should work well in a new `react-collapse@5.0.0` https://github.com/nkbt/react-collapse/releases/tag/v5.0.0
