### ISSUE TITLE
Collapse above?

### ISSUE THREAD

**Issue by ChCosmin** [nkbt/react-collapse#221]
Is there any way to make the collapse expand upwards? Trigger button is in a footer, and when i click it, the collapsed area expands above it, upwards.

**Comment by mitrey** [comment]
have the same question...

**Comment by nkbt** [comment]
Stick your element to the bottom with position:absolute or smth similar, so when height is changing it will go up.
react-collapse only changes height and overflow, everything else is up to your css.
