### ISSUE TITLE
Box-shadow ignoring

### ISSUE THREAD

**Issue by mqklin** [nkbt/react-collapse#232]
I've set some `box-shadow` to `Collapse` children, and it shows only after animation is completed:

![rzcyhc55plqfv2adkf8-rx4lumsvv-na1tnneujc8yrsmmvysj4hxa3vyv-qhnpbzultgr1t2nryvlhfh1yk0lnlsmh0egfbdyhze6lvomai4av1wcwksmudutgzhrrg](https://user-images.githubusercontent.com/9456433/41394662-3b17ea5e-6fc4-11e8-86f7-aa5c7b036896.gif)

How can I show the `box-shadow` right after animation is started?

**Comment by nkbt** [comment]
It is because there is `overflow: hidden` on collapse container. You cannot use anything that goes outside of a collapsible container, so box-shadow will definitely not work. It is by design, sorry there is no way to "fix" it.
