### ISSUE TITLE
[BUG] IE9: 'cancelAnimationFrame' is undefined

### ISSUE THREAD

**Issue by tonoslav** [nkbt/react-collapse#234]
![image](https://user-images.githubusercontent.com/3399021/41784812-1096015c-7641-11e8-98a6-729d5a999e2d.png)

Maybe just add some check

**Comment by tonoslav** [comment]
Its not important to find any alternative, just change this 
https://github.com/nkbt/react-collapse/blob/4f4fbce7c6c07b082dc62062338c9294c656f9df/src/Collapse.js#L123-L125


to 

```js
componentWillUnmount() {
    cancelAnimationFrame && cancelAnimationFrame(this.raf);
}
```

at least :)

**Comment by nkbt** [comment]
I know that it is not difficult at all, but: https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

> After January 12, 2016, Microsoft will no longer provide security updates or technical support for older versions of Internet Explorer

It is 2018 now ;)
