### ISSUE TITLE
Adding a doNotRenderOnLoad / lazyLoad prop

### ISSUE THREAD

**Issue by ro-savage** [nkbt/react-collapse#243]
We currently use react-collapse to hide content that we then render only when it's opened. We then keep it rendered.

This is pretty common for us and while its not much work does make us a bit of logic to each component that could be hidden inside this lib.

Someone is the past suggest a lazilyRender prop as well.

Would you be interested in a PR that adds this functionality through a prop?

It would
1) Not render until `isOpened` is triggered for the first time
2) Keep the rendered content when it is collapsed
3) Then function normally

**Comment by nkbt** [comment]
This should work well with `UnmountClosed`

As new `react-collapse@5.0.0` is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been most likely already solved.

Please feel free to re-open if the issue persists
