### ISSUE TITLE
Quick jump when children contain margins

### ISSUE THREAD

**Issue by tkrugg** [nkbt/react-collapse#246]
**Version**
react-collapse@4.0.3 with react-motion@0.5.2

**Steps to reproduce**
1. Go to https://codepen.io/tkrugg/pen/NVKQEL?editors=1111

2. Toggle open button

**What is expected?**
No jump

**What is actually happening?**
There is jump at the end of the animation, right after the height is set to `auto`.

![Untitled](https://user-images.githubusercontent.com/2982512/57184780-d3574980-6ec0-11e9-864e-0ade92574c23.gif)

**Comment by nkbt** [comment]
Yep, it's by design. see https://github.com/nkbt/react-collapse#behaviour-notes
