### ISSUE TITLE
Remove peerDependencies?

### ISSUE THREAD

**Issue by PavelGavlik** [nkbt/react-collapse#25]
I was trying to install react-collapse with npm@3 and Webpack build failed, because I didn't have react-motion installed (npm@3 doesn't install peerDependencies).

Do you think we could remove peerDependencies? I think we don't need react as well, because it is already included in dependencies.

**Comment by nkbt** [comment]
Thanks for checking out!

Without `react-motion` it is not possible to use `react-collapse`. As well as without `react`. This is exactly the reason peerDependencies are there. But most importantly `peerDependencies` allow you to have potentially incompatible libs (but still working). If we specify React 0.14.0 in deps, you would have (potentially) 2 different `React`s on a page.

NPM 3 made it clear - peerDeps must be installed manually, they are not installed automatically anymore. So just install `react-motion` too.

Probably we need to add this to the readme:

```
npm install --save react react-motion react-collapse
```

**Comment by PavelGavlik** [comment]
Thanks for quick reply! I guess that changing the readme would be the most straightforward solution.

**Comment by nkbt** [comment]
Keen to PR =) ?

**Comment by PavelGavlik** [comment]
Yep, submitted.
