### ISSUE TITLE
Closing animation doesn't work on React <16.3

### ISSUE THREAD

**Issue by catriuspham** [nkbt/react-collapse#253]
The block under doesn't work on older React which makes closing happens instantly without animation.

```js
getSnapshotBeforeUpdate() {
  if (!this.container || !this.content) {
    return null;
  }
  if (this.container.style.height === 'auto') {
    const {clientHeight: contentHeight} = this.content;
    this.container.style.height = `${contentHeight}px`;
  }
  return null;
}
```
My suggestion is to use https://github.com/reactjs/react-lifecycles-compat.

**Comment by nkbt** [comment]
Peer dependency declares ^16.3.0 version, anything prior to that is not expected to work as intended
