### ISSUE TITLE
v5 doesn't work in IE11 anymore

### ISSUE THREAD

**Issue by davidspiess** [nkbt/react-collapse#256]
I upgraded to v5 today and noticed it doesn't work in IE11 anymore, since `Object.assign()` has been used.

**Comment by nkbt** [comment]
Thanks for reporting. That should be an easy fix

**Comment by superlaziness** [comment]
Any update?

**Comment by nkbt** [comment]
Ouch, that’s been a while, got sidetracked by my life right now, will try to get to it soon

Thanks for a reminder

**Comment by superlaziness** [comment]
No pressure :) I guess the easiest way is just getting rid of `Object.assign()` in `index.js`.
Thanks for your useful package!

**Comment by nkbt** [comment]
https://github.com/nkbt/react-collapse/releases/tag/v5.0.1

**Comment by davidspiess** [comment]
Awesome! 🎉
