### ISSUE TITLE
Best way to re-calculate height?

### ISSUE THREAD

**Issue by reintroducing** [nkbt/react-collapse#259]
I've got a Panel component that opens/closes with react-collapse. Inside of it I have a Table component that shows, you guessed it, a table. When resizing the browser down to smaller viewports, the table collapses into Card components which are much taller than the table itself originally was. When I resize it, the height obviously becomes larger and breaks layout of the Panel. 

Is there a good way to re-render the panel to re-calculate the height based on the resized content? Or is my only choice to manually listen to window resize and re-create the whole panel manually? I hope not, but I'm not sure if there is a way around this right now.

**Comment by nkbt** [comment]
1. Short answer probably would be yes - listen to browser resize. 
2. Also check react-element-resize lib
3. Please create some code sandbox as I can only remotely guess what your case is and have almost no clue what you see

**Comment by reintroducing** [comment]
@nkbt I'm not quite sure what happened yesterday that I was seeing this (I have a feeling it may be my HMR not reloading properly when I filed this) but I am not seeing this issue any longer today. Apologies for the noise, but `react-element-resize` looks pretty cool so at least I got that out of this :)

**Comment by nkbt** [comment]
Glad I could help 👍
