### ISSUE TITLE
How to achieve constant speed (pixel/second) for variable heights?

### ISSUE THREAD

**Issue by msikora78** [nkbt/react-collapse#261]
How to achieve constant speed (pixel/second) for variable heights? For example, with `transitionDuration: 500ms` very tall content would open very quickly, but very short content would be opening very slowly. How to achieve constant speed in pixels per second?

**Comment by nkbt** [comment]
I am not sure how possible this is with pure css. You may want to use a bit of JS to do that. Collapse gives you necessary callback so you can apply custom duration based on height.
