### ISSUE TITLE
Safari 13.0.5: height isn't resized correctly

### ISSUE THREAD

**Issue by yepstepz** [nkbt/react-collapse#263]
Hello, I have a list of products, which may have a loader. And sometimes react-collapse doesn't recalculate height from content height to auto after loader quickly dissapears.
Safari Version 13.0.5 (14608.5.12)
macOs Mojave 10.14.6

Tried to reproduce this behavior with demo, here's gif.
![Screen-Recording-2020-03-05-at-1](https://user-images.githubusercontent.com/15925516/75961836-c4bc3300-5ed3-11ea-8797-bea732d2c5d3.gif)

It's not reproducing with Google Chrome.

**Comment by nkbt** [comment]
Thank you. Need to have a look 👀 
I’m myself using safari on mojave, so it should be possible

**Comment by yepstepz** [comment]
Tried to research it. I noticed that this bug reproduced in line 121 Collapse.js: 
`if (hasOpened || hasClosed) { `
onRest method gets both props as false. It happens when you quickly resize content size from big to min as gif shows.
Will try to make codepen, but it’s very tricky heisenbug.

**Comment by nkbt** [comment]
Don't think I can reproduce this. Also quite possible it was some Safari issue, as my version is higher now. It is now `14.0.1` to be precise.
