### ISSUE TITLE
Container not animating

### ISSUE THREAD

**Issue by johnnyBira** [nkbt/react-collapse#264]
I've been using this library in many times before, but for some reason when trying it in my latest project the collapse is not animating.
I tried to remove everything in my page only having a plain button and the Collapse components, but it still dosen't work. The content inside Collapse goes from hidden to visible instantly without any animation.

**Comment by nkbt** [comment]
Most likely you need to add CSS transition as Collapse itself does not longer perform JS-based animation. Check the readme on the details (and maybe migration guide)

**Comment by johnnyBira** [comment]
@nkbt yes that was it!
I was so used to this just working out of the box that I didn't even think to check the readme as thoroughly as I should have.
Thanks for releasing and maintaining this library

**Comment by nkbt** [comment]
Glad I could help!
Cheers
