### ISSUE TITLE
Npm warning for node 4

### ISSUE THREAD

**Issue by texttechne** [nkbt/react-collapse#27]
npm warns that node v5 is required from your package, because `package.json` specifies: 
```
"engines": {
    "node": "^5.0.0"
  }
```
IMO it should be `node: "^4.0.0"`. Node v5 has new experimental features, while v4 is the stable, mature release branch. If you do not make use of any new features it is simply not necessary to restrict your library to the v5 release branch.

**Comment by nkbt** [comment]
5 is stable. Not LTS though. We do use latest stable node 5 everywhere and
I simply cannot afford supporting more then one major version at a time.

You don't need to worry though and ignore NPM warning, since it is UI
library and it does not depend on Node at all. Node is required only for
builds/tests.

**Comment by texttechne** [comment]
Duh, sure. You don't rely on node for your production build. Then please consider dropping the engines specification. Warnings are not meant to be ignored and if too many of those can-be-safely-ignored-warnings are shown, the important ones won't get noticed at all.

BTW: We both made wrong statements: 4 and 5 are *stable*. It's just a matter of release cycles and long term support: https://nodejs.org/en/blog/community/node-v5/

**Comment by nkbt** [comment]
I guess you are right.

Makes sense dropping that entirely and simply putting a note in readme
'development and testing' section.

Thanks for raising.

**Comment by texttechne** [comment]
Thanks for fixing!

**Comment by nkbt** [comment]
Published react-collapse@1.7.0
