### ISSUE TITLE
hasNestedCollapse no longer necessary in v5 yet is used in Nested example

### ISSUE THREAD

**Issue by itsuryev** [nkbt/react-collapse#270]
Hello!

According to docs:
```
- ~~hasNestedCollapse~~ - no longer necessary, as v5 does not care if there are nested Collapse elements, see [example/App/Nested.js](example/App/Nested.js)
```

Yet that very file does use `hasNestedCollapse` prop. 

As there is no such prop in implementation I guess it should be removed in example as well?

**Comment by nkbt** [comment]
I must have missed it in the example, yes it is definitely unnecessary
