### ISSUE TITLE
Animation not working when the Collapse has a parent that it is in modal or something with position fixed

### ISSUE THREAD

**Issue by mahdijirofti** [nkbt/react-collapse#276]
I'm using react-responsive-modal and animation not working

**Comment by nkbt** [comment]
Collapse checks element's height, so if height of element cannot be determined by js it won't work. 
Usually it is working perfectly fine with posititon fixed parents.

Also When you say "not working" what does it even mean? So many thigs may not work as you expect and fixes are all different.

Please debug your element height over time and determined height with collaps (with console log at least).

**Comment by mahdijirofti** [comment]
@nkbt 
I discover my issue and I think this bug is on `react-responsive-modal` side because this package use react portal
