### ISSUE TITLE
The overflow for 'React-collapse--' is overflow:hidden , not overflow:initial for IE11 

### ISSUE THREAD

**Issue by roshmani** [nkbt/react-collapse#280]
The overflow is still hidden with the version 5.0.1 of react-collapse, its giving a problem when for example a form with a dropdown list with a multiple values is used. The value is getting cut on opening the dropdown list.

**Comment by nkbt** [comment]
I don't think there is much out there left supporting ie11.
Even Microsoft's own Teams will drop its support at the end of this month.

As a one-person-do-it-for-free-team I cannot provide support for ie11 and other dead browsers. You're welcome to try fixing it though with a PR

> On August 17, 2020, Microsoft published a timeline indicating that Microsoft Teams will stop supporting Internet Explorer 11 on November 30, 2020 whereas Microsoft 365 products will end Internet Explorer 11 support on August 17, 2021

**Comment by bill-reiss** [comment]
I had this same issue, what is happening from what I can tell is that ie11 doesn't support a CSS value of "initial", and trying to set this value just gets ignored. I fixed it in a wrapper of the control by on open setting the "overflow" CSS property to "visible" when the component is expanded. If someone wants to PR a fix it would probably be a check for IE and if so set the "overflow" property to "visible" or probably "" would work.
