### ISSUE TITLE
Animation doesn't work

### ISSUE THREAD

**Issue by jintak0401** [nkbt/react-collapse#286]
<img width="442" alt="캡처" src="https://user-images.githubusercontent.com/32933980/101901288-2abcb000-3bf4-11eb-9203-f7c696350627.PNG">

Above image is my code. However, animation of <Collapsese> does not apply to its children. What should I do?

**Comment by nkbt** [comment]
Add css transition.

**Comment by jintak0401** [comment]
To where? I add "transition: height 500ms" at both <Collapse> and <HandglassGrid>, but it doesn't work...

**Comment by nkbt** [comment]
To the collapse element

```
.ReactCollapse--collapse {
  transition: height 500ms;
}
```

Also make sure content is actually full height before un-collapsed.

I do not have more context from your code to help better for now.

**Comment by jintak0401** [comment]
Oh, I add that at globals.css, it works!!! Thank you, thank you so much!!

**Comment by nkbt** [comment]
Cheers! Happy it worked out 👍
