### ISSUE TITLE
Collapse horizontally aligned content

### ISSUE THREAD

**Issue by LucusWebsites** [nkbt/react-collapse#292]
First of all thanks for this awesome piece of software!

And is it possible to collapse (animated) horizontally aligned content as well? In my situation I have multiple buttons horizontally aligned next to eachother, some buttons need to be hidden after the user changes some form values.

**Comment by nkbt** [comment]
Hi @LucusWebsites 
Thank you.
There is a feature request I've created long ago #213 which is exactly about it. There is no functionality for this, if you are keen to implement it - would be fantastic

**Comment by LucusWebsites** [comment]
Thanks for the quick answer.

My time is limited but I would love to contribute to software like this.
So small chance I might add the functionality and create a pull request some day.

**Comment by nkbt** [comment]
Wonderful, thank you!
