### ISSUE TITLE
Prop passing suggestion

### ISSUE THREAD

**Issue by reintroducing** [nkbt/react-collapse#299]
I read the documentation about not passing through props, but would it be possible to at the least pass through `data-*` props? These should be safe to pass through as they don't alter/affect the functionality of the component. The current use case for us is that we use `data-test` attributes to get cleaner tests written for our components (and it's a paradigm heavily favorite by Testing Library) but we cannot drill those attributes down into the react-collapse elements. 

My suggestion would be the provide a `data` object in much the same way as you already do `theme` which can then take attribute name/value pairs and translate that to data attributes on the component. you can even provide a prop to change the `data-*` attribute name for more fine grained control. A crude example:
```js
...
theme={{collapse: 'foo', content: 'bar'}}
data={{collapse: 'test-foo', content: 'test-bar'}}
dataAttribute="test"
...
```

This would translate to something like:
```
<div data-test="test-foo">
...
```

If `dataAttribute` would be set to `baz' then the markup would be:
```
<div data-baz="test-foo">
...
```

Alternately, if you don't want to allow changing the dataAttribute (I'd encourage it since it is settable in Testing Library and would provide greater flexibility, I have a use case around this as well if you need convincing but I'll spare you the details), the attribute name can be parsed from the actual data object, so `collapse: 'test-foo'` can be parsed into `data-test="foo"`, but obviously you'd have to establish and document the pattern for how its parsed (you could even say something like `collapse: 'test|test-foo'` would be parsed into `data-test="test-foo"`, but obviously that requires greater explanation.

Regardless, it would be great to implement this on some way/shape/form. Thoughts?

**Comment by nkbt** [comment]
From https://github.com/nkbt/react-collapse#pass-through-props

--- 

### Pass-through props

**IMPORTANT** Collapse does not support any pass-through props, so any non-supported props will be ignored

Because we need to have control over when `Collapse` component is updated and it is not possible or very hard to achieve when any random props can be passed to the component.

**Comment by reintroducing** [comment]
Right, I read that and referenced in my question, but these are data props and not really impactful for the functionality of the component, just to decorate it. Do you still envision the same issue(s) outlined with just data props?

**Comment by nkbt** [comment]
Why not use `theme` for this? I mean it is possible to set any classnames to any of the elements of the component?

```js
<Collapse theme={{collapse: 'foo test-collapse', content: 'bar test-content'}}>
  <div>Content here</div>
</Collapse>
```

**Comment by reintroducing** [comment]
It’s my understanding that theme would make it a class. The purpose of using the data attributes is that we then, for production builds, strip out the data-test attribute using a Babel plugin since the sole purpose of the attributes is to be used during tests. If it’s a className then it makes it more complex to do this cleanly.

**Comment by nkbt** [comment]
Yeah it will be an html `class` attribute in the end

Classnames can be removed the same way any data attributes are removed. Just one example: https://www.npmjs.com/package/babel-plugin-react-remove-classname

**Comment by reintroducing** [comment]
@nkbt understood, this is not the responsibility of this library and as such I'll go ahead and close this. we will work around it in our UI library in other ways. Appreciate the discussion.

**Comment by nkbt** [comment]
Thank you for understanding. I am not enjoying rejecting ideas or prs, but at some point I made a promise to myself to not add functionality that can be achieved outside of the library to avoid infinite feature growth. Had a few examples going south like that.
