### ISSUE TITLE
Basic usage failing

### ISSUE THREAD

**Issue by msimonc** [nkbt/react-collapse#30]
Thanks for this project!

When I wrap a tag in an otherwise working render() function:

```javascript
import { Collapse } from 'react-collapse';
...
return (
				<Collapse isOpened={true}>
					<h3>Cars</h3>
				</Collapse>
			);

```
I get:
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

Dependencies installed, Babel 6 / ES6, webpack build...

**Comment by nkbt** [comment]
`import Collapse from 'react-collapse';`

`react-collapse` exports only one component.

**Comment by msimonc** [comment]
Thanks, but I now get:

Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by nkbt** [comment]
Are you adding `ref` anywhere? To `<Collapse>` for example? That would not work I believe.


Can you clone http://codepen.io/nkbt/pen/MarzEg?editors=101 and put your example there to reproduce the issue?

**Comment by calvinfroedge** [comment]
I am also having this error with latest version of react. Using as follows: 

```
<Collapse isOpened={this.state.expanded}>{this.props.children}</Collapse>
```

**Comment by nkbt** [comment]
@calvinfroedge which version of React you are using?
http://codepen.io/nkbt/pen/MarzEg?editors=101 -- this demo works pretty well with react@0.14.6

<img width="577" alt="20160225-164743" src="https://cloud.githubusercontent.com/assets/175264/13311074/8a33a568-dbdf-11e5-87cb-4f2ec7184a25.png">

**Comment by nkbt** [comment]
I reckon I can close this now...
