### ISSUE TITLE
CSS modules in React app won't affect the rendered Collapse

### ISSUE THREAD

**Issue by hambone01** [nkbt/react-collapse#313]
JS:
<Collapse
          className={styles.ReactCollapseCollapse}
          isOpened={isOpen}
          style={{ transition: 'height 5s !important' }}
        >
        ...
<Collapse/>        

CSS:
.ReactCollapse--collapse {
    max-width: 800px;
    border: 1px solid rgba(3, 169, 244, 0.3);
    border-radius: 10px;
    background-color: rgba(100, 255, 100, 0.1);
    transition: height 5s;
}

For some reason I want to be embarrassed for even asking this question. I have read that the only way to modify the CSS, when using a library that has hard-coded or non-overideable CSS, you have to fork a version of your own. 

Thank you in advance.
sg

**Comment by nkbt** [comment]
You can use theme prop to supply your own classnames. See https://github.com/nkbt/react-collapse?tab=readme-ov-file#theme-proptypesobjectofproptypesstring

**Comment by hambone01** [comment]
Thank you very much. I would like to tell you your software is inspiring as well as useful. I wish I could take that next step and make something useful and reading your code is really fun and inspiring.

Props to you brother.
