### ISSUE TITLE
When collapse is opened by default animation starts from 0 if content is changed

### ISSUE THREAD

**Issue by nkbt** [nkbt/react-collapse#36]
http://codepen.io/nkbt/pen/XXozma?editors=0010

**Comment by GeraldIstar** [comment]
I'm also met this bug several days ago. I'm looking forward for the moment when this bug will be fixed, and I can use this lib.

**Comment by nkbt** [comment]
Hi @GeraldIstar! If you can debug it a bit and find the fix - that would be awesome. I would really appreciate any help!

**Comment by GeraldIstar** [comment]
Looks like problem is near to defaultStyle of Motion component
Here, in most cases compoent start from 0, but some times `height` provided from state is also equal to 0 (not sure, might be my fault).
https://github.com/nkbt/react-collapse/blob/master/src/Collapse.js#L151 
This cause that 0-height is provided to `newStyle` here:
https://github.com/nkbt/react-collapse/blob/master/src/Collapse.js#L169
But I've just spent few time, and can suggest that I missed somthing.

**Comment by davidspiess** [comment]
Any news on this? I'm experiencing the same :(

**Comment by davidspiess** [comment]
The `Motion` component needs to have the same `height` set in `defaultStyle` as in the previously rendered static `div`. It's quite tricky to solve as at the moment there is no way to tell if the previous `render` call was a static one or not. Storing the static height between calls could be a solution but seems quite hacky to me. Any ideas?

**Comment by nkbt** [comment]
@davidspiess I actually store current height between calls, so it is as hacky as hell already ;)

This does not seem like a hugely complicated issue (comparing to the flexbox one, for example). There is a PR, I'll check it asap.

**Comment by nkbt** [comment]
Thanks to @GeraldIstar, it's all good now \o/

**Comment by nkbt** [comment]
```
+ react-collapse@2.2.1
```

https://github.com/nkbt/react-collapse/releases/tag/v2.2.1
