### ISSUE TITLE
Prop for onHeightChange

### ISSUE THREAD

**Issue by jlevycpa** [nkbt/react-collapse#38]
Thanks for the awesome component! I'm trying to use this inside of an absolutely positioned modal which is centered on the screen. When the Collapse component expands, I need to re-center my modal. Ideally the re-centering should happen each time the spring renders so the modal smoothly moves up as the content grows longer.

I can't think of any way to do that except to pass a function into the Collapse component for it to call each time the interpolated height changes.Any other thoughts on how I could approach this?

Thanks,
Jeff

**Comment by nkbt** [comment]
Hi, @jlevycpa 

Thanks for using react-collapse! 

Actually that is an interesting point. I don't think there is currently any indication on when collapse finished animation (either close, or open, or when height changed). As soon as I land the change to use `onRest` of `react-motion` that should be pretty trivial to implement.

I'm going to give this library some love very soon, hopefully in next 2-3 weeks will close outstanding issues.

Meanwhile if you are keen and really need it - feel free to add `onRest` callback (similar to `react-motion`) and submit a PR.

**Comment by nkbt** [comment]
Fixed by #43 
Published as react-collapse@2.2.0

**Comment by jlevycpa** [comment]
This is great. Thanks!

**Comment by nkbt** [comment]
@jlevycpa let me know how it works and if it works well for your case, please! Feel free to open new issue if you find a bug
