### ISSUE TITLE
Re-render nested components

### ISSUE THREAD

**Issue by Frumcheg** [nkbt/react-collapse#40]
ReactCollapse re-render childrens on first animation.

1. Have a nested component with some initial state
2. Change state of this component by UI control
3. Click on toggle
4. Nested component rendered again with initial state

Look: 
![example](https://cloud.githubusercontent.com/assets/2862206/13955133/5fe5558c-f065-11e5-923d-f4e54e71574c.gif)

Touch: http://codepen.io/Frumcheg/pen/pyPzEm

I think, this happend because method `render()` can return 2 differend classes.
When ReactCollapse mounted, `div` returned, when i click on `toggle`, `<Motion>` returned instead.
First solution for me is keep state between mount/unmount in outer variable, or in top level component, but this not best way.
Is it possible always return `<Motion>` class? Why react collapse has flag `renderStatic` inside?

**Comment by nkbt** [comment]
RenderStatic is needed for the case when height is known and should not be measured.

This issue is sort of related to another one. I'm on my phone now and cannot really do anything about it. Will come back home next monday and hopefully will be able to resolve them. There is a PR already. If you can give it a try and check if issue is still there, that would be awesome!

Thanks, Nik

**Comment by nkbt** [comment]
I've updated example to use the most recent versions: http://codepen.io/nkbt/pen/wGZWqG

Still a bug.

**Comment by nkbt** [comment]
Updated  http://codepen.io/nkbt/pen/wGZWqG with react-collapse@2.3.3, cannot reproduce anymore the bug with child component.

There is still an issue with parent component height not being determined properly, so when it closes - it starts from the previous height.

**Comment by nkbt** [comment]
I don't think there is much to do about parent one, since children effectively not changed and any new props were not passed through it, so it cannot figure out that height was changed.


though, I have an idea!

We should determine height __before__ collapsing too.

**Comment by nkbt** [comment]
Just published `react-collapse@next` (not `latest` channel yet until better tested) with full rewrite, which fixes this issue. Give it a shot if you are keen.
