### ISSUE TITLE
No animation after update

### ISSUE THREAD

**Issue by zimt28** [nkbt/react-collapse#44]
After updating from `2.0.0` to `2.1.0`, the `<Collapse>` component opens and closes as expected, but doesn't animate anymore.

**Comment by nkbt** [comment]
Hi, @zimt28!

I've checked several times before release and after release too. I cannot reproduce the issue =(.

Just updated gh-pages example with the latest version: http://nkbt.github.io/react-collapse/example and it works perfectly fine for me (at least in chrome, chrome canary and opera)

**Comment by zimt28** [comment]
Hi @nkbt,

this seems to be an issue with [react-storybook](https://github.com/kadirahq/react-storybook), as I just noticed that it's working as expected in my actual app.

Thanks!

**Comment by nkbt** [comment]
Great!
