### ISSUE TITLE
Animation finished callback

### ISSUE THREAD

**Issue by keyeh** [nkbt/react-collapse#51]
The onRest callback was implemented for `<Motion>` in react-motion v0.4.3.

See:
[The docs](https://github.com/chenglou/react-motion#--onrest---void)
And [the pull request that added it](https://github.com/chenglou/react-motion/pull/273)

It would be great if we could use this to pass a callback when the animation is done.

**Comment by nkbt** [comment]
Yeah, that's been definitely planned, just can't get my hands over it to do a fix. Keen to PR? Would really appreciate it!

**Comment by nkbt** [comment]
Will be fixed in #71

**Comment by nkbt** [comment]
Just published `react-collapse@next` (not `latest` channel yet until better tested) with full rewrite, which fixes this issue. Give it a shot if you are keen.
