### ISSUE TITLE
Usage with react-router?

### ISSUE THREAD

**Issue by FezVrasta** [nkbt/react-collapse#54]
Any advice to use this component to display react-router routes? I'd like to render the router content and then expand it with collapse (and vice versa)

**Comment by nkbt** [comment]
We don't use react-router and use https://www.npmjs.com/package/component-router intstead. Some components are collapsible and they keep their state in URL. Works perfectly fine.

I have very little idea how react-router operates, so cannot really help here.

**Comment by nkbt** [comment]
Closing this for now
