### ISSUE TITLE
Replace height calculation with react-measure

### ISSUE THREAD

**Issue by souporserious** [nkbt/react-collapse#57]
Is this of any interest to you? If it is I can do a PR. I just rewrote the internals of react-measure and have a "slideable" component similar to this one in the examples https://github.com/souporserious/react-measure/blob/master/example/Slideable.jsx

I was able to get around all these issues with it:
https://github.com/nkbt/react-collapse/issues/55
https://github.com/nkbt/react-collapse/issues/40
https://github.com/nkbt/react-collapse/issues/35
https://github.com/nkbt/react-collapse/issues/34
https://github.com/nkbt/react-collapse/issues/31
https://github.com/nkbt/react-collapse/issues/1

**Comment by nkbt** [comment]
Element resize detector is smth that dies not work well in this case. I
also have react-element-resize that is precise and accurate but do not use
it here. React collapse is high perf component that can be and actually is
used for large tables with many collapsible rows.

What could be great (I already mentioned it in another issue) - make height
measurement "backend" configurable, so it is either fast and not always
perfect for many elements, or for 3-5 elements on the screen, always
accurate.

Thanks a lot!

**Comment by souporserious** [comment]
Cool, no worries. Just thought I'd ask :)

**Comment by nkbt** [comment]
That's ok @souporserious! I am following your project and watching what is going on there ;)

**Comment by nkbt** [comment]
I bloody need this stuff in README heh...
