### ISSUE TITLE
React Collapse in A list causes all collapsed items to open when one is clicked

### ISSUE THREAD

**Issue by AdamKyle** [nkbt/react-collapse#58]
This might not be a bug so much as user error, but if you render multiple:

```
import Collapse        from 'react-collapse';

...

<Collapse isOpened={this.props.hidden}>
  ... 
</Collapse>
```

in a list, and then click on one item in the list to trigger it to open, ALL of them will open. Not sure the best approach to get around this. Is there some option or some way where I can say if X is clicked then only open X and not Y and Z

**Comment by nkbt** [comment]
This seem like concern of your app. You define which Collapse is going to be opened or closed =). Collapse gets only one prop `isOpened`. You can have an array of those in your own component and do something like:

```js
<div>
  <Collapse isOpened={!this.props.hidden[0]}>
  ... 
  </Collapse>
  <Collapse isOpened={!this.props.hidden[1]}>
  ... 
  </Collapse>
  ... and so on
</div>
```

**Comment by nkbt** [comment]
Closing this for now, feel free to reopen if you still have issues with this
