### ISSUE TITLE
React 15.2.0 Warning: Unknown prop `onHeightReady` on <div> tag.

### ISSUE THREAD

**Issue by reintroducing** [nkbt/react-collapse#61]
I'm getting this error after I updated to the latest React.  Here is a screenshot of my console (seems to also be an issue in react-height): https://www.dropbox.com/s/frfuoiczc7e2scu/Screenshot%202016-07-02%2013.17.36.png?dl=0

**Comment by nkbt** [comment]
Yep. On it. Thanks!

**Comment by nkbt** [comment]
Published + react-collapse@2.3.1

**Comment by reintroducing** [comment]
Appreciate the quick turnaround, many thanks.

**Comment by nkbt** [comment]
Cheers!
