### ISSUE TITLE
Height problem

### ISSUE THREAD

**Issue by Baransu** [nkbt/react-collapse#64]
I have Collapase component which wraps my SubOrder component: 

```js
             <Collapse
               class="panel-body"
               onHeightReady={(height) => {console.log(height)}}
               isOpened={!collapsed}
               springConfig={presets.noWobble}
             >
               <SubOrder
                 prices={prices}
                 shippingAddress={shippingAddress}
                 {...subOrder}
               />
             </Collapse>

```

The problem is that `height` returns 0 so animations are not working correctly. When i'm looking at Chrome DevTools there is div which is wrapping my component but it has no height so i think it's breaking height calculation. And when I'm inspecting page with React DevTools the same div has `ref=bound setWrapperRefs()`. Am I doing something wrong or it's some `
react-collapse`/`react-height` bug?

EDIT: And also there in no `onRest` event emitted

***
![screen shot 2016-08-04 at 23 33 10](https://cloud.githubusercontent.com/assets/9558691/17419041/dd6b7c8e-5a9b-11e6-962c-f06b028a0dc1.png)
***
![screen shot 2016-08-04 at 23 32 29](https://cloud.githubusercontent.com/assets/9558691/17419046/e0ddb846-5a9b-11e6-9ca9-0486146a3c9c.png)

**Comment by nkbt** [comment]
if your component is absolutely positioned - then it will not work.
The div is necessary to measure content, though content has to have measurable height =) (not be absolute, or be absolute but with hardcoded height and some other weird css conditions)

The other case is if you create your deep nested sub-component dynamically after the fact of height measured. It is not really possible to track with current implementation. There are some ideas around other issues... #34, #1 and so on. Ad explanation why exactly react-height and not react-element-resize (tldr: performance).

I will eventually do something about it, tho I have another fairly large project to complete in my spare time these days and we do not have any issues with collapse on my work to justify fixing it =(.

ReactCollapse has basically a fairly limited use-case at the moment. It does what it was built for pretty well and fast, but there are obviously some use-cases we never though of, that are not working for other people...

**Comment by Baransu** [comment]
It looks like I messed up with Bootstrap Grid system (few missing `.row`) and it fixed the problem.

**Comment by nkbt** [comment]
Phew! 😥
