### ISSUE TITLE
Unnecessary unmount with keepCollapsedContent

### ISSUE THREAD

**Issue by jooj123** [nkbt/react-collapse#66]
Im not 100% convinced this is an issue with react-collapse (maybe react-motion?)

I have noticed that when using the `keepCollapsedContent`, the first time you open - any child components are rendered and then unmounted - but any subsequent open/close there is no longer any unmounting.

Ideally it would never unmount so we dont need another unnecessary rerender after that

**Comment by nkbt** [comment]
That seems like a bug it it actually goes like that. With `keepCollapsedContent` children should be never destroyed.

Do you have an example to reproduce it? Maybe codepen?

Cheers

**Comment by jooj123** [comment]
Reproducing this in code pen is a little different, but i think its related to the same issue:
https://codepen.io/jooj123/pen/qNLXNJ

Notice the unnecessary unmounts, and mounts:
![screen shot 2016-08-11 at 10 58 21 am](https://cloud.githubusercontent.com/assets/1309297/17576054/43d4db4e-5fb2-11e6-933a-6f5ccb24e9fe.png)

**Comment by nkbt** [comment]
Should be fixed with #71, I am adding this to the list of examples

**Comment by jooj123** [comment]
NIce, looking forward to it !

**Comment by nkbt** [comment]
Just published `react-collapse@next` (not `latest` channel yet until better tested) with full rewrite, which fixes this issue. Give it a shot if you are keen.

**Comment by jooj123** [comment]
I just checked it out - everything seems to wok correctly except in my use case for some reason the animation has got a bit clunky, any ideas why that my be? 

Will try and provide another code pen (and submit another issue) if there is a script tag I can use that has the latest version (not sure if there is)

**Comment by nkbt** [comment]
Thanks!


https://npmcdn.com/react-collapse@3.0.0/build/react-collapse.js this would do.  I did some more changes, but not published yet (not that it might change the behaviour anyway)

**Comment by nkbt** [comment]
re-published newer version https://npmcdn.com/react-collapse@3.1.1/build/react-collapse.js 

Probably better to use https://npmcdn.com/react-collapse@next/build/react-collapse.js

**Comment by jooj123** [comment]
I was unable to reproduce the issue in codepen - must be related to my code base which has many nested components with each collapse, will be some time until i can find the issue

**Comment by acarl** [comment]
I just wanted to note that I was able to duplicate this issue in a simple scenario with 4.0.3.

The child content gets unrendered on each collapse.

I switched to react-smooth-collapse as a result.
