### ISSUE TITLE
Make <Collapse/> render a givent DOM element instead of just a div

### ISSUE THREAD

**Issue by phun-ky** [nkbt/react-collapse#68]
Using `<Collapse/>` in a `<ul>` based menu, or inside a native inline element, i.e `<span/>`'s is not semantically correct.  This will also apply if `react-collapse` is to be used instead of a `<nav/>` element, rendering a `<div/>` instead of the semantically correct `<nav/>` element.

Is there a way to bypass this at the project current state, or should we wait for a PR/fix from the owner?

**Comment by nkbt** [comment]
Hi, @phun-ky 
There are some issues doing so. Whole content is wrapped into an extra element that is necessary to measure content height. It cannot be `li` or `span` unfortunately. It is not technically hard to let you choose which element to use, though anything then proper block element will most likely fail to work properly.

https://github.com/nkbt/react-debounce-input/pull/32/files this is a similar change for react-debounce-input - it works fine there.

I believe doing so for react-collapse would significantly increase end-user complexity by adding no value...

Just to illustrate what DOM looks like (approximately):

1. before height is measured
```html
<div class="just-your-component">
  <div class="extra-div-to-measure-height">
    <div class="actual-collapse-wrapper">
       CHILDREN_HERE
    </div>
  </div>
</div >
```
2. after height measured
```html
<div class="just-your-component">
  <div class="actual-collapse-wrapper">
     CHILDREN_HERE
  </div>
</div>
```

So if you want to replace Collapse element with `li` for example, you still need to do somethin with one more wrapper (react-height). Imagine we will reuse `li` for it too. So we end up with:
```
```html
<ul class="just-your-component">
  <li class="extra-div-to-measure-height">
    <li class="actual-collapse-wrapper">
       CHILDREN_HERE
    </li>
  </li>
</ul>
```

That won't be correct `ul > li > li > CHILDREN`. Same if you pass `ul` -- `div > ul > ul > CHILDREN`...

Imagine we are able to set both elements - for height (ul) and for collapse(li)... We end up with

`.just-your-component > ul.react-height > li.collapse > CHILDREN`

On the next moment it will become

`.just-your-component > li.collapse > CHILDREN`


Either way it it not really working well. It won't work for any DOM elements that require particular strict nesting. So apparently we are left with `span` and `div`. As I mentioned using inline `span` will not work  - won't measure height. Doing span but setting it to be `display: block` has pretty much zero  semantical advantage comparing to `div`.

Phew... that was kind of a long explanation

**Comment by nkbt** [comment]
Potentially I can do it now, since DOM structure is now stable. Not convinced on how much useful it is.

Current DOM structure is

```css
div.ReactCollapse--collapse > div.ReactCollapse--content > [children]
```

@phun-ky any ideas how changing `div > div` to something else might be useful?

**Comment by phun-ky** [comment]
Would not `const newTag = document.createElement("[ul|li|div|main|footer|header|article|span|dl")` suffice?
Or somehting more ReactJS-ish from https://facebook.github.io/react/docs/glossary.html

**Comment by nkbt** [comment]
I reckon not `document.createElement` =). JSX are not really DOM elements - they are JS functions.

Technically it can be done exactly the same way as in https://github.com/nkbt/react-debounce-input/pull/32/files, but I really cannot see how it might be useful.

**Comment by phun-ky** [comment]
I find that using semantically correct components to be very useful for accessibility, don't you?

**Comment by nkbt** [comment]
I can understand why, sure, but what I am not so sure about - how exactly. Do you have some examples with double-nested `.collapse > .content` block elements + context around them would make sense when being semantically correct?

So far I can only see something like `.section > article.collapse > div.content > h1` or `section.collapse > div.content`...

I am pretty much totally unaware of any tech aspects of a11y

**Comment by phun-ky** [comment]
Well, if I understand you correctly, there are some cases, the list for example:

    <ul>
      <li>
        Lorum ipsum dolor sit amet. <button type="button" class="collapseToggler" onClick="collapseThis">See all items</button>
      </li>
      <li class="collapse">
        <ul class="content">
          <li>This is collapsed content</li>
          <li>This is collapsed content</li>
          <li>This is collapsed content</li>
        </ul>
      </li>
    </ul>


With `<Collapse/>`:

  <ul>
    <li>
      Lorum ipsum dolor sit amet. <button type="button" class="collapseToggler" onClick="collapseThis">See all items</button>
    </li>
    <Collapse tag="li">
      <ul class="content">
        <li>This is collapsed content</li>
        <li>This is collapsed content</li>
        <li>This is collapsed content</li>
      </ul>
    </Collapse>
  </ul>

Or another scenario with lists:

  <ul>
    <li>
      Lorum ipsum dolor sit amet. <button type="button" class="collapseToggler" onClick="collapseThis">See all items</button>
    </li>
    <li>
      <ul>
        <li>This is NOT collapsed content</li>
        <li>This is NOT collapsed content</li>
        <li>This is NOT collapsed content</li>
      </ul>
      <Collapse tag="ul">
        <li>This is NOT collapsed content</li>
        <li>This is NOT collapsed content</li>
        <li>This is NOT collapsed content</li>
      </Collapse>
    </li>
  </ul>

Or if we could just say that it is inline to prevent block elements to be nested under inline elements:

    <span>
      <Collapse type="inline">...content</Collapse>
    </span>

Which would render:

    <span>
      <span class="collapse">...content</span>
    </span>

Note that `display:block` has to be set on the inline elements to get height/width correctly.

Maybe I am a bit off here.

**Comment by nkbt** [comment]
height cannot be really measured on inline elements. anything what Collapse deals with must be block.

Collapse itself consists of 2 elements `div.collapse > div.content`, those are not "virtual" elements, but actually real DOM, so these examples cannot be possible:
```html
    <Collapse tag="ul">
      <li>This is NOT collapsed content</li>
      <li>This is NOT collapsed content</li>
      <li>This is NOT collapsed content</li>
    </Collapse>


  <Collapse tag="li">
    <ul class="content">
      <li>This is collapsed content</li>
      <li>This is collapsed content</li>
      <li>This is collapsed content</li>
    </ul>
  </Collapse>
```


Something that can be potentially possible:

```html
<ul>
  <li>
    Lorum ipsum dolor sit amet. <button type="button" class="collapseToggler" onClick="collapseThis">See all items</button>
  </li>

  <Collapse elements={{collapse: 'li', content: 'ul'}}>
      <li>This is collapsed content</li>
      <li>This is collapsed content</li>
      <li>This is collapsed content</li>
  </Collapse>
<ul>
```

This will be rendered to:
```html
<ul>
  <li>
    Lorum ipsum dolor sit amet. <button type="button" class="collapseToggler">See all items</button>
  </li>

  <li class="ReactCollapse--collapse">
    <ul class="ReactCollapse--content">
      <li>This is collapsed content</li>
      <li>This is collapsed content</li>
      <li>This is collapsed content</li>
    </ul>
  </li>
<ul>
```

And both `ReactCollapse--collapse` and `ReactCollapse--content` **must** be block elements.

I guess that the last example is quite possible, and implementation should be pretty straightforward. It definitely was not possible before when DOM structure was not stable (it was jumping from 1 wrapper tag to 2 or even 3 depending on current state), but now structure is totally stable - always 2 elements, so we can do it.

I will happily accept PR if you are keen implementing it, since I have one extra ongoing urgent project besides my day job, and will not be able to do any significant changes on other projects in next several weeks.


Thanks for the issue and examples, very helpful

**Comment by phun-ky** [comment]
If you set an inline element, i.e. `<span/>` et al: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements to `display:block`, you can calculate the height just as easily if the element was a block element, `<div/>`

See the example I made here: http://codepen.io/phun-ky/pen/qNzzkQ

**Comment by nkbt** [comment]
sure thing, i did not mean semantically block elements, only in terms of styling, so `span`/`li` is not an issue
