### ISSUE TITLE
Jumps to zero height and flickers from zero to X height

### ISSUE THREAD

**Issue by arush** [nkbt/react-collapse#7]
Hi,
When a Collapse component contains an element with a dynamic height that starts/ends at 0, it causes the Collapse component to jump instead of animate. I believe the following licecap demonstrates the same issue. There's also a flicker when going from 0 to 50.
![react-collapse-bugs](https://cloud.githubusercontent.com/assets/329761/10810128/d85862ca-7dba-11e5-842a-ba4cf87e2989.gif)

**Comment by nkbt** [comment]
ha, I see. That must be related to check that height is actually zero and skip Motion. Looks like a bug.

**Comment by nkbt** [comment]
Published v1.3.0

**Comment by nkbt** [comment]
[Codepen Demo](http://codepen.io/nkbt/pen/MarzEg?editors=101) updated too
