### ISSUE TITLE
`onRest` not being called

### ISSUE THREAD

**Issue by jeroenransijn** [nkbt/react-collapse#79]
I am using `Collapse` with ES6 in my project and it is working so far.
However the `onRest` callback is not being called.

I am using:

```
<Collapse className="VenueContentMap" onRest={() => console.log('rest')}  isOpened={isMapShown} fixedHeight={400}>
</Collapse>
```

Might it be a `react-motion` issue?

This project is very much appreciated btw, reminds of the jQuery.slideToggle days :)

**Comment by nkbt** [comment]
I've found that under certain CSS conditions (`VenueContentMap` has padding set, or some collapse children has margin which "leak" outside of collapse) collapse height does not match content height and it never gets to the "IDLING" state (which is the time it fires "onRest").

This needs to be fixed of course, or at least some warning logged, but meanwhile try to remove paddings/margins from Collapse-related containers and see if it is working. Also you can set a breakpoint in the `componentDidUpdate` in case you want to see that it is never moved into an `IDLING` state.

Initially onRest was just exposed onRest from react-motion, though in the last rewrite it is invoked when Collapse itself is idling.

**Comment by jeroenransijn** [comment]
Thanks for the quick reply. Actually I am not using any margins or padding, or weird CSS for that matter. Initially I loaded Google Maps in there, but I removed that to see if it worked.

This is my reduced test case which still doesn’t work:

```jsx
<Collapse onRest={() => console.log('onRest')} onHeightReady={() => console.log('height ready')} isOpened={isMapShown} fixedHeight={400}>
<div className="VenueContentMap-inner"></div>
</Collapse>
```

```css
.VenueContentMap {
	height: 400px;
	background: white;
}

.VenueContentMap-inner {
	height: 400px;
}
```

Any help is appreciated.

**Comment by jeroenransijn** [comment]
I just tested by removing the `fixedHeight` attribute, and that seemed to work. Maybe an edge in your calculations?

**Comment by nkbt** [comment]
Most likely =(.

At the moment if you fix height of content, you don't really need `fixedHeight` option. I reckon it might have sense to simplify the code of collapse itself, to set height of inner `content` component instead of changing logic. There are no extra calculations anyway (it had some sense in previous implementation, but after rewrite it seems like no real gain)

**Comment by nkbt** [comment]
As new react-collapse@5.0.0 is released https://github.com/nkbt/react-collapse/releases/tag/v5.0.0 this issue has been most likely already solved.

Please feel free to re-open if the issue persists
