### ISSUE TITLE
Transition delayed if embedded in a transition group and isOpened=true on mount

### ISSUE THREAD

**Issue by atombender** [nkbt/react-collapse#84]
Here's a video ([MP4 version](https://www.dropbox.com/s/1zg0ce4dlf1k26w/collapsebug.mp4?dl=0)):

![collapsebug mp4](https://cloud.githubusercontent.com/assets/50314/18218123/952227c6-712e-11e6-855f-9e922175c475.gif)

This is all I'm doing:

``` jsx
<Collapse
  isOpened={true}
  springConfig={{stiffness: 180, damping: 12}}>
  [red box contents]
</Collapse>
```

The entire dialog modal is being wrapped in a transition group. As you can see, the red box is being rendered with a full height, before the motion animation kicks in.

**Comment by nkbt** [comment]
Hi!
I've never use and never planned to use TransitionGroup and have no idea how exactly it does re-render of content and so why this might happen :(
